### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cwida/fsst#2]
I would like to point out that an identifier like “[`_FSST_H_`](https://github.com/cwida/fsst/blob/fffb613071cb44319c0d6b743a8d6eafc2ed2ad7/fsst.h#L48 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by peterboncz** [comment]
sure - fixed

**Comment by elfring** [comment]
Thanks for [your small source code adjustment](https://github.com/cwida/fsst/commit/c4c81971b219b331a954f1b4106f2152e046fff3 "Renaming of an include guard").
