### ISSUE TITLE
Undefined Behaviour Sanitizer Errors

### ISSUE THREAD

**Issue by caustt** [cwida/fsst#4]
Hello,
we are currently working at integrating the FSST Compression into [Hyrise](https://github.com/hyrise/hyrise/pull/2392).
Our CI Sanitizers complain about undefined-behaviour errors that occur in libfsst.hpp. See here:
![image](https://user-images.githubusercontent.com/38725693/129864846-357476da-259d-45bf-9ca6-db3f62eaf7e8.png)

If we set the following cmake compile options we could reproduce those errors also in the fsst repo:

```
add_compile_options(-fsanitize=undefined -fno-sanitize-recover=all)
add_link_options(-fsanitize=undefined -fno-sanitize-recover=all)
```

![image](https://user-images.githubusercontent.com/38725693/129864348-9e814a6c-2452-40d1-83aa-c41e876f999f.png)

We were curious if this is supposed to be like this and we can safely ignore this or if this could cause some issues.

**Comment by Bouncner** [comment]
+ 1

**Comment by caustt** [comment]
Thank you for adding those! Unfortunately the compiler annotations didn't make any difference for us. Also setting the define (FSST_MUST_ALIGN_STORES) doesn't seem to do any difference here.
With or without it, we get the same errors as posted above.

**Comment by peterboncz** [comment]
I should have studied your screenshots better. Apart from the rather crucial unaligned writes in decompression that we are very aware of, there is a much less performance-critical use of an unaligned *load* in libfsst.hpp:287

It is used for creating Symbol objects -- but this plays a role mostly in the calibration/creation of a new dictionary. But, this constructor is likely not performance-critical, not even for dictionary creation.

A solution would be to direct platforms that would crash on misaligned loads to the iterative alternative code that already exists right above that in the define MEMDEBUG (using a new define FSST_MUST_ALIGN_MEMACCESS that would replace FSST_MUST_ALIGN_STORES  to keep things simple).

my question is now the second screenshot which refers to libfsst.hpp:386  
Are you sure your code is identical, because I cannot see unaligned things (in the vicinity) of that location?

My question would be to change MEMDEBUG (libfsst.hpp:82) into FSST_MUST_ALIGN_STORES for the moment, make sure FSST_MUST_ALIGN_STORES is defined, and check your sanitiser results again.

**Comment by peterboncz** [comment]
the latest version contains what I think are the definitive fixes of these sanitiser warnings.

fsst now uses memcpy() where it did unaligned reads and writes before. godbolt suggests that memcpy(dst, src, 8) is translated on all platforms that support it to an unaligned read/write (which is what we want). But our code is lo longer breaking any rules.

**Comment by caustt** [comment]
> I should have studied your screenshots better. Apart from the rather crucial unaligned writes in decompression that we are very aware of, there is a much less performance-critical use of an unaligned _load_ in libfsst.hpp:87+90
> 
> It is used for creating Symbol objects -- but this plays a role mostly in the calibration/creation of a new dictionary. This constructor is likely not performance-critical, not even for dictionary creation.
> 
> A solution would be to direct platforms that would crash on misaligned loads to the iterative alternative code that already exists right above that (libfsst.hpp:83) under the define MEMDEBUG. I would propose using a new define FSST_MUST_ALIGN_MEMACCESS that would replace FSST_MUST_ALIGN_STORES to keep things simple.
> 
> my doubt is now the second screenshot which refers to libfsst.hpp:386
> Are you sure your code is identical, because I cannot see unaligned things (in the vicinity) of that location?
> 
> I thus suggest you to temporarily change MEMDEBUG (libfsst.hpp:82) into FSST_MUST_ALIGN_STORES, make sure FSST_MUST_ALIGN_STORES is defined, and check your sanitiser results again. Would be curious whether these would then go away.
> 
> It would also be better to expose the unaligned access to the compiler by using a fsst_unaligned64_t cast (now introduced in fsst.h) instead of const uint64_t in libfsst.hpp:87+90 and it could even be that this alone could make sanitiser warnings go away. Properly annotating unaligned access gives compilers the best chances to generate correct code for every platform; and defining FSST_MUST_ALIGN_MEMACCESS would be a backstop on platforms where they fail to do so.
> 
> Because, we would prefer to keep using unaligned memory acces, on all relevant platforms (x86, arm64) that support it; as it provides significant benefit in decompression speed.

Your suggestions worked, after setting all the defines you mentioned and changing MEMDEBUG to FSST_MUST_ALIGN_STORES, we got no more alignment issues, thanks a lot!



> the latest version contains what I think are the definitive fixes of these sanitiser warnings.
> 
> fsst now uses memcpy() where it did unaligned reads and writes before. godbolt suggests that memcpy(dst, src, 8) is translated on all platforms that support it to an unaligned read/write (which is what we want). But our code is lo longer breaking any rules.

The latest changes seemed to have fixed most alignment errors, without setting any defines, but we got one last error here though in fsst.h:
![image](https://user-images.githubusercontent.com/38725693/132356469-7dab370d-17c1-4f2a-ac78-a3dbd8ae8468.png)

**Comment by peterboncz** [comment]
Thanks for checking that. Well, indeed I had missed one unaligned memory read. Now fixed.

These changes made the code more portable, but not any slower. Many thanks!
